### ISSUE TITLE
week 5 code review

### ISSUE THREAD

**Issue by snstclair** [snstclair/GigMate#3]
@pawaitemadisoncollege

Week 5 is ready for review finally!

I am loving hibernate more and more, not having to write out my sql is great!

I didn't stumble too much other than forgetting to populate my tables before testing!

My issues have been in motivation and life throwing a few curve balls. I feel like doing this assignment in my project was a great way for me to catch up! Will be getting it launched onto aws in the coming days!

**Comment by pawaitemadisoncollege** [comment]
GenericDao and equals methods and full code coverage?! Oh my!!! Nicely done! Can't wait to see this on aws!

- [x] Think about testing the delete scenarios in one-to-many relationships more fully. For example, if a gig is deleted, what should happen to the band? What if a band is deleted, or a venue? Write tests to make sure whatever **should** happen in the relationships, **does** happen.
