### ISSUE TITLE
Project Design Review 1

### ISSUE THREAD

**Issue by spartan7777** [snstclair/GigMate#4]
# Design/Code Review 1
​
## Project: GigMate
​
### Developer: Sydney St. Clair
​
### Reviewer: Tosan Ogedengbe
​
|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. EVERY item should have *at least* one "kudos" and one suggestion for improvement|
|**Problem Statement**|1. Accurately describes the project's purpose.<br> 2. Is professional and free of typos, slang, etc.<br> 3. Thoroughly explains the problem and the solution.<br> 4. Is understandable by the average person.|The problem statement  accurately describes the purpose for the app and project. You have an idea that you are very passionate about....and it shows. The statement was very professional, and it is easily understandable. A suggestion might be to add into the problem statement the intent to include a way to improve the relationships between venues and bands. That could be a rating system that you could include in the future. That way people can see through the statement that the app is about more than just getting these entities to find each other, but is also about growing their relationships. |
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens. <br>5. Project plan and time log are up-to-date. |The application's description and the ideas on how it will work seem to flow naturally. It was mentioned that the app will utilize a more simple "social media" type of appearance, and that does make sense for how the app will be used. There were no design documents at the time to show us what the app screens would look like. It would have been great to see the ideas on possible backgrounds, button placement, icon and text use, font etc. There was a mention of some messaging features coming to the app as well - and seeing how these messages might look and how they would flow would have been great. |
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model. <br> 2. There are at least two 1-to-many relationships.<br> 3. The model represents good database design. <br>|The database was present and was well designed. The proper relationships and their counts for the database were present and all was good there. There was a known omission of username and password columns in the database, but those were going to be added in later on.  |
|**Code**|1. Proper Maven project structure is used. <br> 2. a .gitignore file for IntelliJ Java projects has been implemented. <br> 3. There is not any redundant or copy/paste code in the JSPs or classes.<br> 4. Classes are appropriately-sized (no monster classes).<br> Property files are used appropriately: no hard-coded values. <br> 5. Logging statements are used rather than System.out.println and printStackTrace (be sure to use a search to look for these!).<br> 6. There are appropriate unit tests/code coverage. <br>|Maven structure was there. There was very efficient code in the project. There was a great looking Generic Dao present and it took care of all redundant code that I could see. The Java Classes were of good size and easy to follow. I did not see any unnecessary hard coded values, logging statements were present as needed, and the proper unit tests were included. |

**Comment by pawaitemadisoncollege** [comment]
@spartan7777 and @snstclair 

One thing to add to this, there are some sneaky System.out.printlns and stack traces out there (examples below - but this may not be all-inclusive).  Don't you love it when instructor-provided code has built-in standards "violations"?  Be sure to replace these with logging statements for checkpoint 2.

<img width="930" alt="Screen Shot 2021-02-26 at 11 16 39 AM" src="https://user-images.githubusercontent.com/13874466/109332852-4d8a5800-7824-11eb-8de0-eedb1f8b358e.png">
<img width="886" alt="Screen Shot 2021-02-26 at 11 16 46 AM" src="https://user-images.githubusercontent.com/13874466/109332856-4ebb8500-7824-11eb-90d2-78052011b023.png">
