### ISSUE TITLE
Code Review 1

### ISSUE THREAD

**Issue by RobIsInSchool** [snstclair/GigMate#5]
# Design/Code Review 1

​

## Project:

Gigmate

### Developer:

Sydney St. Clair

### Reviewer:

​Robert Adams

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. EVERY item should have *at least* one "kudos" and one suggestion for improvement|
|**Problem Statement**|1. Accurately describes the project's purpose.<br> 2. Is professional and free of typos, slang, etc.<br> 3. Thoroughly explains the problem and the solution.<br> 4. Is understandable by the average person.| There's no problem statement on the repo - those can be super useful! But the overall explanation/purpose was clear from the code review. Problem and solution are clear. Understandable by the average person. |
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens. <br>5. Project plan and time log are up-to-date. | N/A |
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model. <br> 2. There are at least two 1-to-many relationships.<br> 3. The model represents good database design. <br>| Database diagram looked straightforward and clear. One-to-many relationships are present. |
|**Code**|1. Proper Maven project structure is used. <br> 2. a .gitignore file for IntelliJ Java projects has been implemented. <br> 3. There is not any redundant or copy/paste code in the JSPs or classes.<br> 4. Classes are appropriately-sized (no monster classes).<br> Property files are used appropriately: no hard-coded values. <br> 5. Logging statements are used rather than System.out.println and printStackTrace (be sure to use a search to look for these!).<br> 6. There are appropriate unit tests/code coverage. | Code looks good. Generic dao is being used which cuts down greatly on redundancy. Database class uses PropertiesLoaderInterface, which is great. Each entity class is tested for full CRUD, which is awesome! | 

  

​

​

​

**Comment by pawaitemadisoncollege** [comment]
@RobIsInSchool and @snstclair 

One thing to add to this, there are some sneaky System.out.printlns and stack traces out there (screenshots below for example - this may not be all-inclusive).  Don't you love it when instructor-provided code has built-in standards "violations"?  Be sure to replace these with logging statement before checkpoint 2.

![Screen Shot 2021-02-26 at 1 25 56 PM](https://user-images.githubusercontent.com/13874466/109345823-584de880-7836-11eb-9b45-fd8e729ba667.png)
![Screen Shot 2021-02-26 at 1 26 09 PM](https://user-images.githubusercontent.com/13874466/109345825-597f1580-7836-11eb-8ade-8796b52cfe3c.png)
