### ISSUE TITLE
week 6 code review

### ISSUE THREAD

**Issue by snstclair** [snstclair/GigMate#6]
@pawaitemadisoncollege I got my project deployed!

I'm pretty good at setting up instances now after I had to redo it a few times.

I was having a lot of issues with logging into my instance, but found a fix that worked. I also had to make some changes in my web.xml and pom.xml so my project would deploy.

I ended up using the link Caleb provided on slack, I didn't see the multiple methods on the post at first.

**Comment by pawaitemadisoncollege** [comment]
Congrats @snstclair! Isn't it cool to see your app out in the cloud! 

Please you add your deployed application's url to the list of indie projects in the student repo and respond here when it's added so that I can check it out. Thanks!
