### ISSUE TITLE
Week 7

### ISSUE THREAD

**Issue by snstclair** [snstclair/GigMate#7]
@pawaitemadisoncollege Finally got week 7 implemented!

I got really hyper-focused on my database messing with dates and times and haven't gotten the issue resolved but did finally disable to tests that weren't passing so I could deploy my project.

After I stopped focusing on my tests that weren't passing and a corrupted vm, I was able to get this material implemented pretty easily.

I used the slack channel when I got stuck. Just a 404 from forgetting to add the tomcat user to my local database and an unneeded forward slash on an href.

**Comment by pawaitemadisoncollege** [comment]
Nice job implementing auth into your project @snstclair! 

- [x] Remember as you add more functionality, to keep adding resources that need to be locked down to the web.xml.
- [x] Also, if there are servlets backing the various secured jsps, be sure to restrict those as well as a savvy user could try to navigate right to the servlet, bypassing the jsp.

**Comment by snstclair** [comment]
I implemented the basics of authentication, I plan on adding a better controller system as I build the project out
