### ISSUE TITLE
Week 9 Activity

### ISSUE THREAD

**Issue by snstclair** [snstclair/GigMate#8]
@pawaitemadisoncollege I got week 9 activity up and running!

I had some issues getting the service up but once I got my pom file sorted and changed the password in my hibernate config file I got it working.

I didn't have many issues implementing this weeks material.

**Comment by pawaitemadisoncollege** [comment]
Great work @snstclair! Many students miss the restful naming standards in this exercise, but you've got that down too! `bands`!
